name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote Charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set target channel
        env:
          PROMOTE_FROM: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTE_FROM}" == "edge -> candidate" ]; then
            echo "promote-from=edge" >> ${GITHUB_ENV}
            echo "promote-to=candidate" >> ${GITHUB_ENV}
          elif [ "${PROMOTE_FROM}" == "candidate -> stable" ]; then
            echo "promote-from=candidate" >> ${GITHUB_ENV}
            echo "promote-to=stable" >> ${GITHUB_ENV}
          fi
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.4.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: latest/${{ env.promote-to }}
          origin-channel: latest/${{ env.promote-from }}
          charmcraft-channel: latest/stable
          base-channel: "22.04"

