name: Promote new set of candidate charms
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  promote-candidate:
    uses: ./.github/workflows/promote-charm.yaml
    with:
      from-risk: beta
      to-risk: candidate
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

