# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
